### ISSUE TITLE
Ensure that SESSION_SECRET is not kept to default value

### ISSUE THREAD

**Issue by sergeychernyshev** [StartupAPI/users#120]
Make sure to test for SESSION_SECRET value being set to default value of '...type.some.random.characters.here...' to make sure people do not accidentally end up with less secure setup.

**Comment by JohnKey9** [comment]
hello,

I have written this
UserConfig::$SESSION_SECRET= '321313^%$£$£s%3Al3ozSdvQ83TtC512RvJ.CibaQoHtaY88jjj&Z?//0H3QOB1kqR8H2A';
but I still get the error belo
`set UserConfig::$SESSION_SECRET variable to a long random string
Session secret is still set to a sample value, change it to some random value`

any suggestion pls?

**Comment by sergeychernyshev** [comment]
Did you set this value in a config file? it is possible that you're setting it after system has initialized.

P.S. please create a separate ticket for it.
