### ISSUE TITLE
registration with email that is already registered

### ISSUE THREAD

**Issue by JohnKey9** [StartupAPI/users#291]
If an email is already registered and anyone tries to register with a different username but same email, the system returns a `fatal error`.

**Comment by sergeychernyshev** [comment]
It's possible - conflict resolution might not be implemented properly - it might be throwing a unified exception that can be caught though.

**Comment by sergeychernyshev** [comment]
Can you provide more details - it looks like we are catching [`ExistingUserException`](https://github.com/StartupAPI/users/blob/master/register.php#L59), but it's possible that not all use-cases are caught.

**Comment by JohnKey9** [comment]
Fatal error: Uncaught Error: Wrong parameters for ExistingUserException([string $message [, long $code [, Throwable $previous = NULL]]]) in /home/domains/vol4/524/2566524/user/htdocs/users/classes/AuthenticationModule.php:275 Stack trace: #0 /home/domains/vol4/524/2566524/user/htdocs/users/classes/AuthenticationModule.php(275): Exception->__construct(Object(User), 'User already ex...') #1 /home/domains/vol4/524/2566524/user/htdocs/users/classes/AuthenticationModule.php(316): AuthenticationException->__construct(Object(User), 'User already ex...', 0, Array) #2 /home/domains/vol4/524/2566524/user/htdocs/users/modules/usernamepass/index.php(295): ExistingUserException->__construct(Object(User), 'User already ex...', 0, Array) #3 /home/domains/vol4/524/2566524/user/htdocs/users/register.php(41): UsernamePasswordAuthenticationModule->processRegistration(Array, true) #4 {main} thrown in /home/domains/vol4/524/2566524/user/htdocs/users/classes/AuthenticationModule.php on line 275

**Comment by JohnKey9** [comment]
you were right, error was a bit strange, I have reverted the files to the original version.
thanks a lot for your help
